### PR TITLE
Chore: GUI QOL

### PR DESCRIPTION
**Pull request by Cheshire92**
This is a long one.. But also relatively basic. Basically taken some feedback from various games and users into account and changed the following:

- Add a ClientConfiguration (config.json on the client) option to enable/disable most of the below features.
- Added a context menu to inventory items. (Text and options change depending on current state and item type, ie. equip, use, learn or bank, trade, sell)
- Added a context menu to spells in the spellbook.
- Added a context menu to equipment.
- Added a context menu to bag items.
- Added a context menu to bank items.
- Added a context menu to trade items.
- Added a context menu to shop items.
- Added a context menu to chat messages.
- Disabled interacting / clicking on the opposing trade side. (This didn't do anything, but you could do it for some reason)
- Made single, double and right clicking consistent between what they do in various item related menus.
- Fill in stack amount automatically when withdrawing from the bank.
- Fill in stack amount automatically when withdrawing from a bag.
- Added the ability to use/equip/drop items while interacting with a trade, bag, bank or shop.
- Added the ability to drag and drop items between inventory and bank.
- Fixed the trade item panels not showing the proper item colour.
- Added distinction between to and from on PMs in both text and colour.
- Added a login notification to friends coming online when enabled in the server config.
- Added a slider version of numeric input for moving items.
- Attempt to calculate how many items you can buy from a shop when the item is stackable automatically.

It's a lot of random Quality of Life stuff, all the context menus can be disabled if someone really hates change and they can revert back to the default intersect methods through the client config.json. Didn't feel like this was a setting appropriate for the server.. Nor for the options menu, I can imagine a dev wants to ship their game in a specific way but it shouldn't be impossible for a user to change this.

Image
Image
Image
Image
Image
Image
Image

Resource files: https://www.ascensiongamedev.com/resources/filehost/d008bba2d9ff6a7cae8d289f73fdadda.zip

### CODE REVIEW

**Comment by lucas-tardivo-dart** [comment]
As you asked for, pitching here the idea of slightly change the PM colors between sender/receiver for a better visual distinction :P

**Comment by Cheshire92** [comment]
Some random comments I've gotten:

1. It's currently slower to deposit due to the extra click, add a deposit all button without confirmation?
2. Add option to enable/disable the context menus in game settings?

**Comment by Cheshire92** [comment]
Nightmare fixed a bug with displaying text input boxes.. might be related to this? Not heard anything about that yet.

**Comment by Cheshire92** [comment]
Some people want to see an option to return single click to use items/spells back.

**Comment by Cheshire92** [comment]
Apparently the value input crashes when you leave the 0 in and type stuff after that in Nightmare. Might be worth a looksie.

**Comment by Cheshire92** [comment]
Fixed an issue with numerical input values getting lost when they got too close to the Int32 cap in #1047

**Review by Arufonsu — APPROVED** [review]

**Review by lodicolo — APPROVED** [review]

**Pull request merged**
