### PR TITLE
Hide quantity on single-stackable items

### LINKED ISSUE #804: Server configuration to not show a stackable item's quantity if there is only 1 of that item.
**Is your feature request related to a problem? Please describe.**
Following a "Runescape" design, some users may want to only stack most items when they're placed in a bank. The stackable implementation as-is is useful for implementing this, however, it looks a bit ugly having a (1) next to all of these items that aren't _truly_ stackable when not in a bank.

**Describe the solution you'd like**
It would be nice to just have a server config value that can hide the display of an item's quantity if the item's quantity is <= 1.

### PR DESCRIPTION
**Pull request by AlexVild**
Resolves #804

### CODE REVIEW

**Comment by jcsnider** [comment]
While I appreciate the PR I don't think this needs to be an option. Just hiding the quantity if < 1 is probably fine.

@Cheshire92 thoughts?

**Comment by Cheshire92** [comment]
I'd also say it doesn't need to be an option. 
I doubt anyone is really attached to seeing they've got one item in their inventory.

**Comment by AlexVild** [comment]
Lol, that's fair. I'll get to updating that and ping y'all when it's gone.

**Comment by AlexVild** [comment]
@jcsnider @Cheshire92 It is done

**Review by Cheshire92 — DISMISSED** [review]

**Comment by jcsnider** [comment]
Should these changes apply to Bags as well?

Also can we do <= 1 instead of == 1. I have a bad feeling that there might be some older/legacy cases where you can have a non stackable item and quantity equals 0.

**Comment by AlexVild** [comment]
Lemme check on bags. Otherwise, lol, sure, I'll make that change :)

**Comment by AlexVild** [comment]
@jcsnider Made the logical change you requested; otherwise you were right about bags. Additionally, I added the logic to the trade window, and to the loot window.

**Review by jcsnider — APPROVED** [review]

**Pull request merged**
