### PR TITLE
fix: StatRange Vision in Crafting

### PR DESCRIPTION
**Pull request by cydyn**
Fix: #2356 
Fix logic for showing statrange and statgive in crafting
The photos show two cases: Statgive + Statrange and StatGive alone, in the second case only Statgive is set.
It does not show 0 to 0 when statrange is not set and only statgive is set.

Zrzut ekranu 2024-07-30 194456
Zrzut ekranu 2024-07-30 194516
Zrzut ekranu 2024-07-30 194715
Zrzut ekranu 2024-07-30 194753

### CODE REVIEW

**Comment by cydyn** [comment]
I open new PR because old no update

**Comment by Arufonsu** [comment]
https://github.com/AscensionGameDev/Intersect-Engine/blob/main/CONTRIBUTING.md#commit-message-and-pull-request-title-quality

**Comment by cydyn** [comment]
@Arufonsu I corrected the PR title and updated it to the new version. is everything OK now?

**Comment by lodicolo** [comment]
Closing in favor of #2438 which fixes the underlying issue as well as makes an additional correction

**Pull request closed without merging**
