### PR TITLE
fix #1344: force show the ui when user input is required

### LINKED ISSUE #1344: bug: hidden ui does not reappear when user input is required
### Description

If the ui is toggled to be hidden then it doesn't start rendering when chat, event dialogs, bags, banks, trading, crafting, or shopping is open and needs the users attention.

### Steps to Reproduce

1. Toggle UI Off
2. Open Bank In Game

### Version with bug

v7.1.22

### Last version that worked well

Unknown

### Affected platforms

Windows, macOS, Linux

### Did you find any workaround?

N/A

### Relevant log output

```shell
N/A
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

### PR DESCRIPTION
**Pull request by jcsnider**
This resolves #1344 

I found that the UI elements although hidden could still be closed, so the extra code changes in this pr fixes that as well.

### CODE REVIEW

**Review by Arufonsu — APPROVED** [review]
tested and confirmed to be working as intended 👍🏽 

https://user-images.githubusercontent.com/17498701/175697831-fb1003e5-d67d-419f-b604-89d0241c0306.mp4

**Review by WeylonSantana — APPROVED** [review]

**Comment by Arufonsu** [comment]
Just a doubt: would this disallow us from hiding specific UI elements from view on specific situations?
ie. i was currently hiding every UI element except for the dialogue window during event dialogue for the sake of minimalism and ease of usage and reading.

**Comment by Arufonsu** [comment]
Just a wondering: would this disallow us from hiding specific UI elements from view on specific situations?
ie. i was currently hiding every UI element except for the dialogue window during event dialogue for the sake of minimalism and ease of usage and reading.

**Comment by jcsnider** [comment]
This doesn't force specific ui elements to show. It only forces the UI to render when an element is open that requires interaction.

**Review by lodicolo — APPROVED** [review]

**Pull request merged**
