### PR TITLE
Added OnUpdate callback for plugins

### PR DESCRIPTION
**Pull request by celojevic**

### CODE REVIEW

**Comment by jcsnider** [comment]
This should be targeting the development branch instead of prerelease. I can try to change the target but it might bring over more than just your single commit, in which case we will need to have this PR remade.

**Comment by lodicolo** [comment]
> This should be targeting the development branch instead of prerelease. I can try to change the target but it might bring over more than just your single commit, in which case we will need to have this PR remade.

Yes, based on the commit history this should be remade. Only 02ad0ef should be in this PR.

**Review by lodicolo — CHANGES_REQUESTED** [review]
This should have been done as part of `ILifecycleHelper`.

Doing it this way mixes up the independence of services from the "main thread" that runs the tight-loop.

Services should boostrap, start, and stop. They are in charge of deciding how and when to "update".

In this case it is more of an event and should follow the same pattern as the `LifecycleChangeState` event in `IClientLifecycleHelper`/`ClientLifecycleHelper`.

**Comment by celojevic** [comment]
Ok, I'll remake it to use a Lifecycle event and have it target the development branch.

**Pull request closed without merging**
