### PR TITLE
Add a connection and logged in user cap.

### LINKED ISSUE #77: Connection/Player Count Limiting
**Depends on**: #63 

**Is your feature request related to a problem? Please describe.**
The server does not have a connection limit, nor a player limit, and will accept connections and players up until it runs out of resources.

**Describe the solution you'd like**
Server should:
- Have the ability to limit concurrent connections (not logged in, "Connections")
  - Should be configurable
  - Should immediately disconnect clients that request a connection beyond this threshold with `NetworkStatus.ServerFull`
- Have the ability to limit concurrent active connections (logged in, "Players")
  - Should be configurable
  - Should reject logins but not terminate the connection (and in a future separate issue can be expanded upon for login queues)

**Additional context**
See #63 for server status details request

### PR DESCRIPTION
**Pull request by Azurebeats**
Resolves #77

### CODE REVIEW

**Comment by jcsnider** [comment]
My request would be to also make it show a "Full" indicator where it shows the server status on the main menu.

I think I'd have he client recheck every 10 seconds or so, but if the server is full it would read "Server Status: Online (Full)" at the bottom left of the main menu and disable the login/register buttons.

**Comment by Azurebeats** [comment]
Panda's original PR already added a full status that shows on the bottom left when it's full of connections.
As for players, there's no handler for that right now I think?

**Review by lodicolo — APPROVED** [review]

**Comment by lodicolo** [comment]
I have no problem with the changes, @jcsnider?

**Comment by jcsnider** [comment]
Tested just now. Works fine.

**Pull request merged**
