### PR TITLE
PVP Team Node (Need testing)

### PR DESCRIPTION
**Pull request by RuyHiroTama**
Allows you to configure friendly fire. Players with the same team ID will not receive damage, and players with ID=-1 will not receive damage and take part in pvp.

Fixed: ID -1 made players immortal when they themselves could deal damage

### CODE REVIEW

**Review by Mighty-Professional — APPROVED** [review]

**Comment by Mighty-Professional** [comment]
Do you mind signing your commit? If you dont know how let me know and I can do it.

**Comment by WeylonSantana** [comment]
Also send us a video of how it is currently working, how party combat was affected, how guild combat was affected and the like.

**Comment by RuyHiroTama** [comment]
> Also send us a video of how it is currently working, how party combat was affected, how guild combat was affected and the like.

At the moment I have no one to test this with and record a video with..

**Comment by RuyHiroTama** [comment]
> Do you mind signing your commit? If you dont know how let me know and I can do it.
> Then just commit anything to this branch and it should be signed.

Uff, I haven't learned this yet, I need to watch some videos about Github..

**Comment by WeylonSantana** [comment]
> At the moment I have no one to test this with and record a video with..

Are you unable to open 2 or more accounts?

**Comment by RuyHiroTama** [comment]
> Are you unable to open 2 or more accounts?

I didn't think about it :0

**Review by Arufonsu — CHANGES_REQUESTED** [review]
- Okay, first of all, this is a brand new feature, and there's been no discussion along with the community regarding this.
- If you want to contribute along with us, you need to follow our contributing conventions, code conventions, naming conventions and code of conduct [here](https://github.com/AscensionGameDev/Intersect-Engine/blob/development/CONTRIBUTING.md)
- For now, I'm gonna have to close this PR as invalid: it doesn't met our naming conventions, it should of been a discussion along with the community, prior becoming a feature request with it's corresponding PR. This also is unable to explain us what the feature does in detail, how it behaves, a video showing off the feature, example of possible use cases, etc.

**Pull request closed without merging**
