### PR TITLE
Cleanup client framework

### PR DESCRIPTION
**Pull request by lodicolo**

### CODE REVIEW

**Comment by Azurebeats** [comment]
This seems to function, but loading the game after logging in appears to be SIGNIFICANTLY slower.
It freezes the entire client for about 3-4 seconds for me now on a black screen before it gets to the game window.

**Comment by Azurebeats** [comment]
As a matter of fact, loading a new tileset swapping between maps takes 1-2 seconds as well for me.

**Comment by lodicolo** [comment]
I suppose that explains what I was seeing yesterday, I'll have to dig through the loading logic.

**Comment by lodicolo** [comment]
Reopening this on a separate branch

**Pull request closed without merging**
