### PR TITLE
Admin Actions: Improves Feedback and Authority checks

### LINKED ISSUE #1061: Moderators can Ban Administrators
**Describe the bug**
Moderators can ban admins. This seems like a flaw in design.

**Version Encountered**

0.7.x

**To Reproduce**
1. Be a moderator
2. Select an admin and ban them

**Expected behavior**
A moderator should be told "You don't have permission to do that" or something

### PR DESCRIPTION
**Pull request by Arufonsu**
* Applied panda's [partial re-implementation](https://github.com/AscensionGameDev/Intersect-Engine/commit/04673626e0d0324733ead22d2607dd09a08970fa) (with somes changes).

* Removed unreachable code from the UserActivityHistory (??' left operand is never null, so we don't need Guid.Empty).

* From now on, bans are always announced globally.

* From now on, mutes are always announced globally.

* Adds ability to Ban/Unban & Mute/Unmute **even** if the target is Offline.

* Adds ability to Unban/Unmute in game by using the target's **player name**. 
  (Unban/Unmute doesn't requires you to know the username of the player anymore.)
  
* Added feedback messages for whenever we try to Unban/Unmute a player that's not Banned/Muted.

* Improved feedback messages by adding colours to their font.
  (   Warning/errors > Red    **|**     Sucess > Green or Global Msgs )

* Added UserActivityHistory for ingame BanFail, Kill, KillFail, Mute, MuteFail, Kick and KickFail.
  
* Added authority level checks with feedback messages for in game actions: WarpToMeAction, Ban, Kick, Kill and Mute
  (Should resolve #1061)
  
* **[NOT TESTED]** Added authority level checks with feedback messages for the **API**: Ban, Kick, Kill and Mute.
  (Need help from experienced users/devs with testing this one !)

### In game authority level checks for: WarpToMeAction, Ban, Kick, Kill and Mute (Solves #1061)
imagen
(Example: Mods are unable to Ban, Kick, Kill, Mute nor warp Admins to them, due to the lack of authority they have over them.)

### Feedback improvements for Ban/Unban.
imagen
This PR also allows us to Un-ban players by using their player's _Names_ instead of their _Usernames_! this feels more consistent and allows it for an easier management since we won't have to look over the database anymore for the banned player's Username. Uban action will also check up if the target is not banned, sending a proper informative message since we can't "unban" someone that's not banned.

### Feedback improvements for Mute/Umute.
imagen
Same as before, unmute will check wether the target is muted or not, if is not muted, we don't need to unmute the target.

Also, with this update, we won't see error logs in the server since we won't hit into this issue anymore:
imagen

### In both of the previously mentioned cases ^, we now check up if the player _exists_ 
(Ban and Mute can be performed despite the online status of players now. so instead of checking and announcing their online status to whoever is performing the action, we are going to simply check and inform to the action performer if they exist.)
imagen

### CODE REVIEW

**Comment by blinkuz** [comment]
I can help you test the api, I'm going to write you on discord.

**Review by AlexVild — APPROVED** [review]
As far as _I'm_ aware, this looks good. But also the permissions/authority area is shockingly complex, so I don't know if anything is being violated here.

**Comment by Arufonsu** [comment]
> t also the permissions/authority area is shockingly complex, so I don't know if anything is being violated here.

Still need help by testing the API power restrictions, i probably went a bit farther than what we actually needed, but still, a lot of things were lacking of permission and authority checks.

**Review by lodicolo — APPROVED** [review]

**Comment by Arufonsu** [comment]
_Reminder for the Dev branch testers:_ 
The API actions **are not fully tested yet**.

_( will edit / remove this whenever the API actions are fully tested )_

**Pull request merged**
