### PR TITLE
feat: editor cursor sprites

### PR DESCRIPTION
**Pull request by Arufonsu**
Reitroducing #1797 after #1882
with bug fixes for crash and early clickpoint setup

### CODE REVIEW

**Comment by lodicolo** [comment]
Build to test: https://www.ascensiongamedev.com/resources/filehost/4d6f0c163c7462f539b4f8b06dff24da.zip

**Comment by Arufonsu** [comment]
imagen

**Comment by Arufonsu** [comment]
Assets: https://github.com/AscensionGameDev/Intersect-Assets/pull/45

**Pull request merged**
