### PR TITLE
Block events from leaving map when moving diagonally

### LINKED ISSUE #1791: bug: Event NPC become duplicated
### Description

When the npc created by event walks to the border of some other map, he gets duplicated for some reason, i dont know if this is happening only in my project, that is very old database, since 2018 i think, but the image of my forum post tells everything. 

https://www.ascensiongamedev.com/topic/6821-event-npc-become-duplicated/

[https://ascensiongamedev.com/resources/filehost/499b21841f309fc62155c0c5061b5d4a.mp4](https://www.ascensiongamedev.com/resources/filehost/499b21841f309fc62155c0c5061b5d4a.mp4)

### Steps to Reproduce

in editor, create a npc event and puts he to walk often
create the event close to the border of the map
wait 5min and go at this map, with your character, in game.
see the bug happening

### Version with bug

7.1.120

### Last version that worked well

7.1.119

### Affected platforms

Windows

### Did you find any workaround?

create the event npc in the middle of the map and put him to walk not very often, but still bugging 

### Relevant log output

_No response_

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

### PR DESCRIPTION
**Pull request by jcsnider**
Possibly resolves #1791 

Will be looking for testers to confirm

### CODE REVIEW

**Comment by lodicolo** [comment]
@jcsnider Can you change this to modify PR #1826 instead (and if that PR is ok to you, you can merge it)?

This PR just adds more work to the other one.

**Comment by NikoCummings** [comment]
I tested the build and can confirm the event duplication bug is fixed.

**Comment by lodicolo** [comment]
I didn't remember that I may have already fixed this in [v0.7.2-beta.26](https://github.com/AscensionGameDev/Intersect-Engine/releases/tag/v0.7.2-beta.26), can you verify? @jcsnider

**Comment by lodicolo** [comment]
https://discord.com/channels/363106200243535872/941435736534679602/1141766005509599252

Tested by Weylon, #1826 supersedes this

**Pull request closed without merging**
