### PR TITLE
[Feature] Global EXP Gain Modifier

### PR DESCRIPTION
**Pull request by Bioblaze**
This is a Feature PR for Allowing a Global EXP Gain Modifier in the Config, as well as allowing it to be modified from the Console itself.

https://www.ascensiongamedev.com/topic/5808-beta-6-global-exp-modifierw-console-support/

I made a Ticket about it here: https://github.com/AscensionGameDev/Intersect-Engine/issues/589

### CODE REVIEW

**Comment by blinkuz** [comment]
Have you considered making it tied to the event system? to be able to change the global modify in game? that would give many possibilities to increase it under certain automatic conditions of the game itself.

**Comment by Khaikaa** [comment]
Actually, instead of making it accessible inside the game(which may be a good add as well), giving api support would be very cool so third parties software can automate when to change and by which value. Lets say you want to add double exp each weekend, you could write 2 lines of code to your api manager and automatize it

**Comment by Arufonsu** [comment]
> 
> 
> Actually, instead of making it accessible inside the game(which may be a good add as well), giving api support would be very cool so third parties software can automate when to change and by which value. Lets say you want to add double exp each weekend, you could write 2 lines of code to your api manager and automatize it

that's actually neat, Crontab!

**Comment by Bioblaze** [comment]
kk doing that now so you want it in the event system, and the api manager. 
I also want to beable to change it from the editor so I'm adding that bit now. Or maybe I'll wait on that bit and just add wht you guys want.

**Comment by Bioblaze** [comment]
Added the API Manager bit, Trying to figure out the event system idk where to even look for it @.@

**Review by blinkuz — APPROVED** [review]

**Comment by Bioblaze** [comment]
I'm still trying to get the Event System working, Here is a Patch can anyone validate i'm doing it right? Pleases?

https://diffy.org/diff/y92w2blozuoenebdxr7tx1or

**Comment by Bioblaze** [comment]
@blinkuz can you accept the PR, i'm working on another Patch that is Large based off development+this patch, for changing Server Options, and things. I'm also adding some Additional Events too the Event System. So I want to put that into another PR if you don't mind.

**Comment by blinkuz** [comment]
@Bioblaze  Unfortunately I can not accept your changes since only devs with write permissions can do it, hahaha I have been waiting for 1 week for them to accept or deny one that I made in collaboration with arufonsu for the tags and nobody has said anything like that, if you are sure that Your functionality works, I recommend you send your other PR as something separate, keep in mind that if your functions are not generic enough and useful for multiple projects, they will not be accepted by the main devs.

**Comment by jcsnider** [comment]
I'll be pulling from this and making a different PR for it soon. We do not want to merge in that first version of the Tags system, and there are a few tweaks that I'd like to make to your setup here. Regardless thanks so much for the PR and please keep them coming ^^

**Comment by Bioblaze** [comment]
WOOT! XD I thought you guys weren't active. <3 Now that I know your accepting PRs :D i'll start pushing ALOT of stuff LOL

**Comment by Bioblaze** [comment]
Do you want me to update the current code so it has no conflicts with the current main branch @jcsnider ?

**Comment by jcsnider** [comment]
We'll be very picky about what we accept, we want stuff that will be used by /most/ projects. And these past several months we've been more focused on bug fixes and solving critical performance issues.

Feel free to either update this PR or create a new one that is cleanly based on the latest dev, I'll provide commentary/stuff we should change and then get it merged in.

**Comment by Cheshire92** [comment]
Considering this hasn't seen any activity in like 5 months I'll be closing this.
No point keeping it open, can always refer back to it later.

**Pull request closed without merging**
