### PR TITLE
Option to lose XP when dying

### PR DESCRIPTION
**Pull request by dhmhc**
I think now I did it correctly, I noticed an error in the repositories when sending the pull

It resolves: #722

### CODE REVIEW

**Comment by jcsnider** [comment]
Need one that PRs from your development into our development instead of into the prerelease branches.

**Comment by jcsnider** [comment]
As an aside.. I dont know why this is messing with the .net framework version as well.. it shouldn't need to.

**Comment by dhmhc** [comment]
> Precisa de um PRs de seu desenvolvimento para o nosso desenvolvimento, em vez de nos ramos de pré-lançamento.



> Need one that PRs from your development into our development instead of into the prerelease branches.

sorry i don't know how to do this.

**Comment by dhmhc** [comment]
> As an aside.. I dont know why this is messing with the .net framework version as well.. it shouldn't need to.

I do not understand too. but always when low it tries to convert to a previous version

**Pull request closed without merging**
