### PR TITLE
Option to lose XP when dying

### PR DESCRIPTION
**Pull request by dhmhc**
I don't know if I'm doing it right, I'm sorry if the way I'm doing it is invalid

It resolves: #722

### CODE REVIEW

**Comment by dhmhc** [comment]
@jcsnider Sorry I never made a pull request like this, I sent the change via GitHub Desktop to my repository, right after, I tried to make a pull request to your source

**Comment by blinkuz** [comment]
It seems to me that you have not uploaded the PR correctly, apart from that the Main branch from where you are trying to send is not the same as the prerelease, main = 6.2 so it is very likely that you will have to delete it.

**Comment by jcsnider** [comment]
We do want all PRs to target the development branch and we based on that so we aren't committing or recommitting hundreds of commits.

**Comment by dhmhc** [comment]
right, I opened another pull with the correct commit, I had requested a pull from main to prerelease. you can close this pull, the most recent I sent this correct.

**Pull request closed without merging**
